# Site Settings
title: My Resume
url: 'http://betoca.github.io'
baseurl: '/' #change it according to your repository name

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6

#Profile information
name: Alberto Rodriguez
tagline: Senior Big Data Developer
pic: profile.jpg  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'Summarise your career here lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean
commodo ligula eget dolor aenean massa. Cum sociis natoque penatibus et magnis dis parturient
montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu.'

#sidebar links
email: betoca@gmail.com
phone: (385) 495-2793
website: blog.webjeda.com #do not add http://
linkedin: alberto-rodriguez
github: betoca
twitter: '@betrocar'
#Update all the sections by editing the files inside _data folder.

# Tracker
analytics: UA-18649684-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
