# Site Settings
title: 'Alberto Rodriguez Carrasco'
url: 'http://betoca.github.io'
baseurl: '/' #change it according to your repository name

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6

#Profile information
name: Alberto Rodriguez
tagline: Senior Big Data Developer
pic: profile.jpg  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: "With the vision to become a highly skilled software architect, I've been providing expertise on full life cycle development tasks of data-oriented systems for enterprises facilitating data analysis. Constantly looking for ways to improve the ongoing solution as well as providing business users and clients with insight regarding the technologies involved."

#sidebar links
#email: betoca@gmail.com
#phone: (385) 495-2793
website: betoca.github.io #do not add http://
linkedin: alberto-rodriguez
github: betoca
#twitter: '@betrocar'
#Update all the sections by editing the files inside _data folder.

# Tracker
analytics: UA-111937442-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
